<?php
$pageTitle=$pageTitle??'StratEdge Pronos — Analyses et journal';
$pageDescription=$pageDescription??'Analyses sportives, méthode et résultats. Explorez le journal StratEdge et découvrez nos offres football, tennis et multisports.';
$pagePath=$pagePath??'/';$pageActive=$pageActive??'accueil';
?>
<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title><?= front_h($pageTitle) ?></title><meta name="description" content="<?= front_h($pageDescription) ?>">
<?php if(!empty($frontNoIndex)): ?><meta name="robots" content="noindex,nofollow"><?php endif; ?>
<link rel="canonical" href="https://stratedgepronos.fr<?= front_h($pagePath) ?>"><meta property="og:locale" content="fr_FR"><meta property="og:site_name" content="StratEdge Pronos"><meta property="og:type" content="<?= $pageActive==='article'?'article':'website' ?>"><meta property="og:title" content="<?= front_h($pageTitle) ?>"><meta property="og:description" content="<?= front_h($pageDescription) ?>"><meta property="og:url" content="https://stratedgepronos.fr<?= front_h($pagePath) ?>"><meta property="og:image" content="https://stratedgepronos.fr/assets/images/logo%20site.png"><meta property="og:image:alt" content="StratEdge Pronos — Analyses et journal"><meta name="twitter:card" content="summary_large_image">
<?php if($pageActive==='article' && isset($post) && empty($frontPreview)): ?>
<script type="application/ld+json"><?= json_encode(['@context'=>'https://schema.org','@type'=>'BlogPosting','headline'=>$post['data']['title'],'description'=>$post['data']['summary'],'datePublished'=>$post['publish_at'],'dateModified'=>$post['updated_at'],'inLanguage'=>'fr','mainEntityOfPage'=>'https://stratedgepronos.fr'.$pagePath,'image'=>'https://stratedgepronos.fr/assets/images/logo%20site.png','author'=>['@type'=>'Organization','name'=>$post['data']['author']],'publisher'=>['@type'=>'Organization','name'=>'StratEdge Pronos','url'=>'https://stratedgepronos.fr/']],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_QUOT|JSON_HEX_APOS) ?></script>
<?php endif; ?>
<link rel="icon" href="/assets/images/mascotte.png" type="image/png"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Orbitron:wght@400;500;600;700;900&family=Rajdhani:wght@400;500;600;700&family=Space+Mono:wght@400;700&display=swap" rel="stylesheet">
<link rel="stylesheet" href="/assets/public-site/site.css?v=20261002owner"><link rel="stylesheet" href="/assets/public-site/owner-theme.css?v=20261002owner"><script src="/assets/public-site/site.js?v=20261002owner" defer></script></head>
<body class="front page-<?= front_h($pageActive) ?>"><a class="skip" href="#contenu">Aller au contenu</a><div class="read-progress" aria-hidden="true"></div>
<header class="site-header"><div class="wrap header-inner"><a href="<?= front_link('/') ?>" class="brand" aria-label="StratEdge, accueil"><img class="owner-brand-logo" src="/assets/images/logo%20site.png" width="180" height="45" alt="StratEdge Pronos"></a>
<button class="menu-toggle" aria-expanded="false" aria-controls="public-nav" type="button"><span>Menu</span><svg width="22" height="22" viewBox="0 0 22 22" fill="none" stroke="currentColor" aria-hidden="true"><path d="M2 7h18M2 15h18"/></svg></button>
<nav id="public-nav" class="public-nav" aria-label="Navigation principale"><?php foreach(['/journal.php'=>['journal','Le journal'],'/methode.php'=>['methode','La méthode'],'/historique.php'=>['resultats','Les résultats'],'/offres.php'=>['offres','Les offres']] as $url=>$item): ?><a href="<?= front_link($url) ?>" <?= $pageActive===$item[0]?'aria-current="page"':'' ?>><?= $item[1] ?></a><?php endforeach; ?><a class="nav-account" href="<?= $frontMember?'/dashboard.php':front_link('/login.php') ?>"><?= $frontMember?'Mon espace':'Connexion' ?> <span aria-hidden="true">↗</span></a></nav></div></header>
<main id="contenu">
