CREATE TABLE IF NOT EXISTS nowpayments_orders (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  order_id VARCHAR(100) NOT NULL UNIQUE,
  membre_id INT UNSIGNED NOT NULL,
  pack_key VARCHAR(20) NOT NULL,
  prix DECIMAL(6,2) NOT NULL,
  invoice_id VARCHAR(100) DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  credited_at DATETIME DEFAULT NULL,
  INDEX idx_membre (membre_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
