<?php require __DIR__.'/../header.php'; ?>
<section class="hero" data-lens="terrain">
  <picture class="hero-image"><img src="/assets/public-site/night-pitch.webp" width="1536" height="1024" alt="Illustration d’un terrain de football éclairé la nuit, vu du ciel" fetchpriority="high"></picture>
  <div class="hero-shade" aria-hidden="true"></div>
  <div class="wrap hero-shell">
    <div class="hero-meta"><span class="eyebrow">Le regard StratEdge</span><span class="eyebrow">Football · Tennis · Multisports</span></div>
    <h1>LE JEU,<br><em>autrement.</em></h1>
    <div class="hero-bottom"><div class="hero-copy"><p>Le frisson du sport.<br>Le recul de l’analyse.</p><span>Des chiffres, du terrain, du contexte.<br>Pour comprendre avant de décider.</span><a class="button" href="<?= front_link('/journal.php') ?>">Explorer le journal <?= front_arrow() ?></a></div>
      <div class="lens-console" hidden><span class="eyebrow">Changez de regard</span><div class="lens-switch" role="group" aria-label="Lecture du terrain"><button type="button" data-view="terrain" aria-pressed="true">Le terrain</button><button type="button" data-view="lecture" aria-pressed="false">La lecture <span aria-hidden="true">↗</span></button></div><p class="lens-explanation" aria-live="polite">Un match se regarde. Une décision se construit.</p></div>
    </div>
    <span class="scene-caption">Création visuelle StratEdge · scène illustrative</span>
  </div>
  <div class="tactical-overlay" aria-hidden="true"><svg viewBox="0 0 1440 820" preserveAspectRatio="xMidYMid slice"><g class="tactic-lines" fill="none" stroke="currentColor"><path class="tactic-path" d="M830 488C965 480 898 265 1070 275S1210 390 1300 420"/><path d="m1272 400 28 20-31 12"/><ellipse cx="960" cy="367" rx="117" ry="138" stroke-dasharray="5 9"/><circle class="tactic-pulse" cx="1070" cy="275" r="24"/><circle cx="830" cy="488" r="18"/><path d="M815 488h30m-15-15v30M1120 515l22 22m0-22-22 22"/></g></svg><span class="tactic-label label-a">01 / Observer les tendances</span><span class="tactic-label label-b">02 / Vérifier le contexte</span><span class="tactic-label label-c">03 / Évaluer le prix</span></div>
</section>
<div class="edition-rail wrap"><span><i aria-hidden="true"></i> Le sport mérite un regard de plus.</span><a href="#journal">La suite se lit ici <span aria-hidden="true">↓</span></a></div>
<section id="journal" class="section wrap home-journal"><div class="section-head" data-reveal><div><span class="eyebrow">01 — Le journal en accès libre</span><h2 class="section-title">À la <em>une.</em></h2></div><p>Ce que les scores ne racontent pas.<br>Analyses, débriefs et culture de la décision.</p><a class="circle-link" href="<?= front_link('/journal.php') ?>" aria-label="Voir toutes les publications"><?= front_arrow() ?></a></div><?php if($posts): ?><div class="journal-grid"><?php front_journal_tiles(array_slice($posts,0,3)); ?></div><?php else: ?><p class="empty"><?= $frontUnavailable?'Le journal est momentanément indisponible. Revenez dans quelques instants.':'Les premières publications arrivent ici. Découvrez déjà notre méthode.' ?> <a class="text-link" href="/methode.php">Lire la méthode →</a></p><?php endif; ?></section>
<section class="manifesto" id="methode"><div class="wrap manifesto-grid"><div class="manifesto-title" data-reveal><span class="eyebrow">02 — Dans la tête de l’analyse</span><h2>DU BRUIT.<br>DES CHIFFRES.<br><em>Du sens.</em></h2><p>Une tendance attire l’œil.<br>La méthode fait le tri.</p><a class="button dark" href="<?= front_link('/methode.php') ?>">Ouvrir le carnet de méthode <?= front_arrow() ?></a><svg class="hand-arrow" viewBox="0 0 240 110" fill="none" aria-hidden="true"><path d="M10 20c100-45 100 100 210 45m-36-14 39 11-18 29" stroke="currentColor" stroke-width="2"/></svg></div><div class="method-steps"><div class="method-step"><span class="step-number">01</span><div><h3>Les chiffres ont une histoire.</h3><p>Source, période, nombre de matchs. Domicile et extérieur. On commence par savoir ce que l’on regarde.</p></div></div><div class="method-step"><span class="step-number">02</span><div><h3>Le terrain a le dernier mot.</h3><p>Absences, compositions, calendrier, conditions de jeu : remettre les moyennes dans leur contexte.</p></div></div><div class="method-step"><span class="step-number">03</span><div><h3>Parfois, le bon pari est de passer.</h3><p>Un prix insuffisant ou trop d’inconnues ? La sélection peut s’arrêter là. Aucun quota à remplir.</p></div></div><div class="method-footnote"><span aria-hidden="true">✳</span><p>Une analyse explique une décision.<br>Elle ne supprime jamais l’incertitude.</p></div></div></div></section>
<section class="section wrap proof-layout"><div data-reveal><span class="eyebrow">03 — Les comptes sont ouverts</span><h2 class="section-title">La suite ?<br><em>On l’assume.</em></h2><p class="section-copy">Les victoires. Les défaites. Les paris annulés.<br>Un bilan se lit en entier.</p><a class="text-link" href="<?= front_link('/historique.php') ?>">Consulter tous les résultats <?= front_arrow() ?></a></div><div class="proof-sheet"><span class="eyebrow">Le registre StratEdge <span aria-hidden="true">↗</span></span><?php if(!empty($resultStats)&&($resultStats['wins']+$resultStats['losses']+$resultStats['voids'])>0): ?><div class="proof-stats"><div class="proof-stat"><strong><?= $resultStats['wins']+$resultStats['losses'] ?></strong><span>paris gagnés ou perdus enregistrés</span></div><div class="proof-stat"><strong><?= $resultStats['rate']===null?'—':number_format($resultStats['rate'],1,',',' ') ?><small>%</small></strong><span>de réussite, hors paris annulés</span></div></div><p class="proof-note">Historique du <?= front_date($resultStats['from']) ?> au <?= front_date($resultStats['to']) ?> · Tous les univers. Le taux de réussite n’est pas une mesure de rentabilité. Résultats renseignés par StratEdge.</p><?php else: ?><div class="empty"><p><?= $frontUnavailable?'Les chiffres sont temporairement indisponibles.':'Les résultats renseignés apparaîtront ici. Aucun taux n’est affiché sans historique.' ?></p></div><?php endif; ?></div></section>
<section class="club-invite"><div class="wrap club-grid"><div><span class="eyebrow">À chacun son terrain</span><h2>PRENEZ<br><em>de la hauteur.</em></h2><p>Du Multisports au Tennis, trouvez le format<br>qui correspond à votre façon de suivre le jeu.</p><a class="button" href="<?= front_link('/offres.php') ?>">Découvrir les offres <?= front_arrow() ?></a></div><div class="ticket-stack" aria-label="Multisports, Tennis, Fun et VIP"><a class="club-ticket ticket-multi" href="<?= front_link('/offres.php#multi') ?>"><span class="ticket-small">STRATEDGE / ACCÈS MEMBRE</span><strong>MULTISPORTS</strong><span>Le jeu, sur tous les terrains. ↗</span></a><a class="club-ticket ticket-tennis" href="<?= front_link('/offres.php#tennis') ?>"><span class="ticket-small">STRATEDGE / ACCÈS MEMBRE</span><strong>TENNIS</strong><span>Chaque surface a son histoire. ↗</span></a><a class="club-ticket ticket-vip" href="<?= front_link('/offres.php#vip') ?>"><span class="ticket-small">STRATEDGE / ACCÈS MEMBRE</span><strong>VIP MAX</strong><span>Explorez le contenu de l’offre. ↗</span></a><a class="ticket-fun" href="<?= front_link('/offres.php#fun') ?>">Et l’univers Fun <span aria-hidden="true">↗</span></a></div></div></section>
<section class="section wrap faq-layout"><div><span class="eyebrow">Avant le coup d’envoi</span><h2 class="section-title">On en<br><em>parle ?</em></h2></div><div class="faq"><details><summary>Qu’est-ce qui est accessible gratuitement ?</summary><p>Le journal, la méthode, le catalogue des offres et la page de résultats sont publics. Les analyses réservées aux membres restent dans leur espace.</p></details><details><summary>Une sélection est-elle publiée chaque jour ?</summary><p>Non. Les données disponibles, le calendrier et les critères d’analyse déterminent les sélections. Une journée sans pari est une décision possible, pas un engagement manqué.</p></details><details><summary>Les analyses garantissent-elles un gain ?</summary><p>Non. Le sport reste incertain et toute mise peut être perdue. Les résultats passés ne préjugent pas des résultats futurs.</p></details><details><summary>Pourquoi publier aussi des explications ?</summary><p>Pour permettre de comprendre une décision, ses hypothèses et ses limites. Le journal distingue les guides, les analyses, les débriefs et les coulisses.</p></details></div></section>
<?php require __DIR__.'/../footer.php'; ?>
