<?php
// Included only after match.php has checked authentication and ownership.
if (!isset($assessment, $m)) { return; }
$f = $assessment['features'];
$format = static function ($value, string $suffix = ''): string { return $value === null ? '—' : number_format($value, 1, ',', ' ') . $suffix; };
?>
<section class="lab-panel"><div class="lab-section-head"><div><div class="lab-eyebrow">Diagnostic du moteur V2</div><h2><?= $pick ? 'Pourquoi cette piste passe les contrôles' : 'Pourquoi le moteur s’abstient' ?></h2><p><?= lab_h($assessment['explanation']) ?></p></div></div>
<?php if ($pick): ?><div class="lab-stats"><div><small>Prix théorique du modèle</small><strong><?= number_format($pick['fair_odds'], 2, ',', ' ') ?></strong><span>cote calculée · modèle non calibré</span></div><div><small>Écart au marché normalisé</small><strong><?= $pick['edge'] === null ? '—' : lab_p($pick['edge']) ?></strong><span>écart de probabilité en points</span></div><div><small>Scénario défavorable</small><strong><?= lab_p($pick['stress_ev']) ?></strong><span>espérance théorique à la cote importée</span></div></div>
<p>Le prix minimal selon les contrôles d’espérance et de sensibilité est de <strong><?= number_format($pick['minimum_price'], 2, ',', ' ') ?></strong>. La fréquence observée de ce marché est <?= $pick['observed_probability'] === null ? 'absente de cet export' : lab_p($pick['observed_probability']) ?>.</p>
<?php else: ?><p>Les motifs sont indiqués marché par marché dans le tableau ci-dessous. Une cote élevée ne suffit pas à créer une opportunité.</p><?php endif; ?>
<details><summary>Lire les critères de sélection</summary><p>Cote entre 1,60 et 3,50 ; estimation au moins égale à 50 % ; espérance du modèle d’au moins +4 % ; écart d’au moins 2,5 points au marché normalisé ; espérance non négative dans les scénarios testés. Les incohérences importantes et les échantillons de moins de huit matchs bloquent la sélection.</p><p class="lab-muted">Sensibilité testée avec des intensités de buts diminuées ou augmentées de 15 %, et deux autres poids de la moyenne de ligue. Ce sont des scénarios, pas un intervalle de confiance. Ces paramètres sont expérimentaux et n’ont pas été optimisés sur un historique de résultats.</p></details></section>
<section class="lab-panel"><div class="lab-eyebrow">Le profil des équipes</div><h2>Production offensive et résistance défensive</h2><div class="lab-table-scroll"><table><thead><tr><th>Statistique de l’export</th><th><?= lab_h($m['home']) ?> · domicile</th><th><?= lab_h($m['away']) ?> · extérieur</th></tr></thead><tbody>
<?php foreach (['shots' => ['Tirs produits / match', ''], 'sot' => ['Tirs cadrés produits / match', ''], 'shots_against' => ['Tirs concédés / match', ''], 'sot_against' => ['Tirs cadrés concédés / match', ''], 'cs' => ['Clean sheets', ' %'], 'fts' => ['Matchs sans marquer', ' %'], 'possession' => ['Possession moyenne', ' %'], 'ppg' => ['Points par match', '']] as $key => [$label, $suffix]): ?><tr><td><?= lab_h($label) ?></td><td><?= $format($f['home_' . $key], $suffix) ?></td><td><?= $format($f['away_' . $key], $suffix) ?></td></tr><?php endforeach; ?>
</tbody></table></div><p class="lab-muted">Moyenne de buts de la ligue : <?= $format($f['league_avg']) ?>. Fréquence globale +2,5 : <?= $format($f['over25'], ' %') ?>. BTTS : <?= $format($f['btts'], ' %') ?>.</p><p class="lab-muted">Les agrégats ne contiennent ni les dix rencontres détaillées, ni les xG, ni les compositions. Ils ne permettent pas de mesurer précisément la récence ou la force des adversaires.</p></section>
