<?php if ($selectedMatches):
$chatMatches = [];
foreach ($selectedMatches as $item) {
    $chatMatches[] = array_intersect_key($item, array_flip(['home', 'away', 'league', 'kickoff', 'pick', 'stats', 'footystats']));
}
$chatPrompt = "Tu es mon analyste football prématch. Voici les paris qui ont passé mes critères statistiques PackBall et FootyStats. Analyse toi-même le contexte de CHAQUE pari avec des recherches web actuelles et des sources datées. Vérifie d’abord l’identité, la compétition et la date exacte du match. Examine les deux équipes : compositions officielles ou probables, blessures, suspensions et remplaçants ; matchs précédents et suivants, repos, déplacements, LDC et autres coupes, risque de rotation ; enjeux et opposition tactique ; météo au stade à l’heure du match et pelouse ; situation documentée du club et de l’entraîneur. Distingue faits confirmés, hypothèses et inconnues. Relie chaque point au marché proposé. Ne transforme pas une rumeur en fait ni une absence d’information en signal favorable. Si le match a commencé, indique analyse prématch impossible et n’utilise pas son résultat pour valider rétrospectivement le pari.\n\nPour chaque match, rends une décision RETENU / À ATTENDRE / ÉCARTÉ, avec les raisons favorables et défavorables, les inconnues déterminantes, les vérifications restantes et les liens sources. Sans compositions officielles ou en présence d’une inconnue déterminante, reste À ATTENDRE. Ne fabrique pas de probabilité corrigée et ne promets aucune réussite. Les probabilités ci-dessous sont expérimentales ; les cotes sont celles de l’export, pas nécessairement celles disponibles maintenant. Termine par les seuls paris retenus au format Match / Bet / Cote exportée / Motif.\n\nDonnées exportées le " . gmdate('c') . " (horaires des matchs avec décalage UTC) :\n" . json_encode($chatMatches, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES | JSON_THROW_ON_ERROR);
?>
<section class="lab-panel lab-form"><h2>Analyser ces paris dans ChatGPT</h2><p>Copie le prompt et les <?= count($chatMatches) ?> sélections avec leurs statistiques et cotes, puis colle-les dans ta conversation.</p><button type="button" class="lab-button" id="lab-copy-chat">Copier les matchs + le prompt</button><span id="lab-copy-status" role="status"></span><details><summary>Voir le texte à copier</summary><textarea id="lab-chat-export" rows="12" readonly aria-label="Prompt et matchs pour ChatGPT"><?= lab_h($chatPrompt) ?></textarea></details></section>
<?php endif; ?>
