<?php
declare(strict_types=1);
require __DIR__ . '/bootstrap.php';
require __DIR__ . '/layout.php';
$run = null; $events = []; $recent = [];
try {
    if (!$labError) {
        $recent = $labStore->recent($labOwner);
        $id = (string)($_GET['id'] ?? ($recent[0]['id'] ?? ''));
        if ($id !== '') { $run = $labStore->get($id, $labOwner); if ($run['kind'] !== 'analysis') { throw new InvalidArgumentException(); } $events = lab_latest($labStore->events($id, $labOwner)); }
    }
} catch (Throwable $e) { $labError = 'Analyse introuvable ou inaccessible.'; $run = null; }
lab_start('Ta journée, analysée', 'analyses');
if ($labError) { lab_end(); exit; }
if (!$run): ?><section class="lab-empty"><div class="lab-empty-icon"><?= lab_icon('analyses', 27) ?></div><div class="lab-eyebrow">Ta première journée</div><h2>Chaque sélection commence par les données.</h2><p>Importe tes statistiques PackBall pour comparer les paris et consulter leur analyse.</p><a class="lab-button" href="<?= lab_h($labBase) ?>import.php">Importer PackBall</a></section><?php else: $analysis = $run['data']['analysis']; ?>
<?php if (isset($run['data']['import'])): ?><p class="lab-meta"><?= lab_icon('check', 16) ?> <?= lab_h($run['data']['import']['filename']) ?> · <?= $run['data']['import']['rows'] ?> lignes importées · Statistiques + cotes · Heure de Paris</p><?php endif; ?>
<form method="get" class="lab-run-select"><label>Journée d’analyse<select name="id"><?php foreach ($recent as $r): ?><option value="<?= lab_h($r['id']) ?>" <?= $run['id'] === $r['id'] ? 'selected' : '' ?>><?= lab_h($r['created_at']) ?></option><?php endforeach; ?></select></label><button class="lab-button lab-secondary">Afficher</button></form>
<div class="lab-stats"><div><small>La journée</small><strong><?= count($analysis['matches']) ?></strong><span>matchs analysés</span></div><div><small>Marchés admissibles</small><strong><?= count(array_filter($analysis['matches'], static function ($m) { return $m['pick'] !== null; })) ?></strong><span>pistes à examiner</span></div><div><small>Qualité des données</small><strong><?= count($analysis['errors']) ?></strong><span>lignes signalées</span></div></div>
<?php if (!$analysis['matches']): ?><p class="lab-notice">Aucun match à venir n’a pu être analysé dans ce fichier. Consulte les lignes signalées ci-dessous ou charge un export plus récent.</p><?php endif; ?>
<?php if (isset($analysis['selection_policy'])): ?><p class="lab-notice"><strong>Moteur V2 · Cotes de 1,60 à 3,50.</strong> Classement selon la résistance du prix aux scénarios défavorables. Les compositions et absences restent à vérifier avant toute décision.</p><?php else: ?><p class="lab-notice">Archive du moteur initial. Recharge ton CSV pour utiliser le moteur V2.</p><?php endif; ?>
<p class="lab-notice">Probabilités expérimentales calculées à partir des statistiques. Le contexte doit être examiné sur chaque fiche. Le classement ne démontre pas la rentabilité.</p>
<div class="lab-filter"><label>Filtrer les matchs<input type="search" id="lab-search" placeholder="Équipe ou compétition"></label><span class="lab-muted">Généré le <?= lab_h($analysis['generated_at']) ?></span></div>
<p class="lab-notice" id="lab-no-results" hidden>Aucun match ne correspond à ta recherche.</p><div class="lab-match-list"><?php foreach ($analysis['matches'] as $rank => $m): $pick = $m['pick']; $past = strtotime($m['kickoff']) <= time(); $decision = $events[$m['key']]['context']['data']['decision'] ?? 'pending'; ?>
<article class="lab-match" data-lab-search="<?= lab_h($m['home'] . ' ' . $m['away'] . ' ' . $m['league']) ?>"><div class="lab-rank"><?= str_pad((string)($rank + 1), 2, '0', STR_PAD_LEFT) ?></div><div class="lab-match-body"><div class="lab-meta"><?= lab_h($m['league']) ?> · <?= lab_h((new DateTimeImmutable($m['kickoff']))->setTimezone(new DateTimeZone('Europe/Paris'))->format('d/m H:i')) ?> Paris</div><h2><a href="<?= lab_h($labBase . 'match.php?id=' . $run['id'] . '&match=' . $m['key']) ?>"><?= lab_h($m['home']) ?> <span>—</span> <?= lab_h($m['away']) ?></a></h2><p><?= lab_h($pick['label'] ?? 'Aucun pari retenu') ?></p><?php if (isset($m['assessment'])): ?><p class="lab-muted"><?= lab_h($m['assessment']['explanation']) ?></p><?php endif; ?><div class="lab-flags"><span><?= $past ? 'Match commencé · archive' : 'Prématch' ?></span><span><?= $decision === 'retained' ? 'Retenu par vous' : ($decision === 'excluded' ? 'Écarté par vous' : 'Contexte à examiner') ?></span></div></div><div class="lab-prob"><?php if ($pick): ?><strong><?= lab_p($pick['probability']) ?></strong><span>estimation du modèle</span><small><?= $pick['odds'] === null ? 'Cote non fournie' : 'Cote exportée ' . number_format($pick['odds'], 2, ',', ' ') ?></small><?php if (isset($pick['stress_ev'])): ?><span>Espérance en scénario prudent : <?= lab_p($pick['stress_ev']) ?></span><?php endif; ?><?php else: ?>—<?php endif; ?></div></article><?php endforeach; ?></div>
<?php if ($analysis['errors']): ?><details class="lab-panel"><summary>Lignes non analysées / erreurs de cotes</summary><ul><?php foreach ($analysis['errors'] as $e): ?><li><?= lab_h($e['file'] . ' · ligne ' . $e['row'] . ' : ' . $e['message']) ?></li><?php endforeach; ?></ul></details><?php endif; ?>
<?php endif; lab_end(); ?>
