<?php
declare(strict_types=1);
require __DIR__ . '/bootstrap.php';
require __DIR__ . '/layout.php';
$run = null; $events = []; $recent = [];
try {
    if (!$labError) {
        $recent = $labStore->recent($labOwner);
        $id = (string)($_GET['id'] ?? ($recent[0]['id'] ?? ''));
        if ($id !== '') { $run = $labStore->get($id, $labOwner); if ($run['kind'] !== 'analysis') { throw new InvalidArgumentException(); } $events = lab_latest($labStore->events($id, $labOwner)); }
    }
} catch (Throwable $e) { $labError = 'Analyse introuvable ou inaccessible.'; $run = null; }
lab_start('Ta journée, analysée', 'analyses');
if ($labError) { lab_end(); exit; }
if (!$run): ?><section class="lab-empty"><div class="lab-empty-icon"><?= lab_icon('analyses', 27) ?></div><div class="lab-eyebrow">Ta première journée</div><h2>Chaque sélection commence par les données.</h2><p>Importe tes statistiques PackBall pour comparer les paris et consulter leur analyse.</p><a class="lab-button" href="<?= lab_h($labBase) ?>import.php">Importer PackBall</a></section><?php else: $analysis = $run['data']['analysis'];
$selectedMatches = array_values(array_filter($analysis['matches'], static function ($m) { return $m['pick'] !== null; }));
usort($selectedMatches, static function ($a, $b) {
    return ($b['pick']['probability'] <=> $a['pick']['probability']) ?: strcmp($a['kickoff'], $b['kickoff']) ?: strcmp($a['key'], $b['key']);
}); ?>
<?php if (isset($run['data']['import'])): ?><p class="lab-meta"><?= lab_icon('check', 16) ?> <?= lab_h($run['data']['import']['filename']) ?> · <?= $run['data']['import']['rows'] ?> lignes importées · Statistiques + cotes · Heure de Paris</p><?php endif; ?>
<form method="get" class="lab-run-select"><label>Journée d’analyse<select name="id"><?php foreach ($recent as $r): ?><option value="<?= lab_h($r['id']) ?>" <?= $run['id'] === $r['id'] ? 'selected' : '' ?>><?= lab_h($r['created_at']) ?></option><?php endforeach; ?></select></label><button class="lab-button lab-secondary">Afficher</button></form>
<div class="lab-stats"><div><small>La journée</small><strong><?= count($analysis['matches']) ?></strong><span>matchs analysés</span></div><div><small>Marchés admissibles</small><strong><?= count(array_filter($analysis['matches'], static function ($m) { return $m['pick'] !== null; })) ?></strong><span>pistes à examiner</span></div><div><small>Qualité des données</small><strong><?= count($analysis['errors']) ?></strong><span>lignes signalées</span></div></div>
<?php if (isset($analysis['footystats'])): $fsSummary = $analysis['footystats']; ?>
<section class="lab-panel"><div class="lab-eyebrow">Couverture FootyStats</div><h2><?= (int)$fsSummary['enriched'] ?> / <?= count($analysis['matches']) ?> matchs enrichis</h2><p><?= (int)$fsSummary['unavailable'] ?> match(s) sans bilans exploitables. Ces matchs ne figurent pas dans la sélection.</p><?php if ($fsSummary['unavailable']): ?><p class="lab-muted">Une donnée manquante ne signifie pas que le match a été écarté après une analyse complète. Après correction, relance l’analyse depuis le fichier déjà enregistré.</p><form method="post" action="<?= lab_h($labBase) ?>action.php"><?= lab_token() ?><input type="hidden" name="action" value="packball_retry"><input type="hidden" name="id" value="<?= lab_h($run['id']) ?>"><button class="lab-button lab-secondary">Relancer avec FootyStats</button></form><?php endif; ?></section>
<?php endif; ?>
<?php if (!$analysis['matches']): ?><p class="lab-notice">Aucun match à venir n’a pu être analysé dans ce fichier. Consulte les lignes signalées ci-dessous ou charge un export plus récent.</p><?php endif; ?>
<?php if (isset($analysis['selection_policy'])): ?><p class="lab-notice"><strong>Moteur V2 · Cotes de 1,60 à 3,50.</strong> Sélection selon la résistance du prix aux scénarios défavorables. Affichage par probabilité statistique décroissante. Les compositions et absences restent à vérifier avant toute décision.</p><?php else: ?><p class="lab-notice">Archive du moteur initial. Recharge ton CSV pour utiliser le moteur V2.</p><?php endif; ?>
<p class="lab-notice">Copie les sélections ci-dessous dans une conversation ChatGPT pour l’analyse approfondie. Le site calcule les statistiques ; aucun appel API GPT n’est effectué.</p>
<?php require __DIR__ . '/chat-export.php'; ?>
<?php if (!$selectedMatches && $analysis['matches']): ?><p class="lab-notice">Aucun pari ne passe les critères pour cette journée. Les motifs de chaque absence de sélection sont disponibles dans « Matchs non retenus ».</p><?php endif; ?>
<div class="lab-filter"><label>Filtrer les matchs<input type="search" id="lab-search" placeholder="Équipe ou compétition"></label><span class="lab-muted">Généré le <?= lab_h($analysis['generated_at']) ?></span></div>
<p class="lab-notice" id="lab-no-results" hidden>Aucun match ne correspond à ta recherche.</p><div class="lab-match-list"><?php foreach ($selectedMatches as $rank => $m): $pick = $m['pick']; $diagnostic = \StratEdgeLab\DecisionEngine::diagnostic($m); $past = strtotime($m['kickoff']) <= time(); $decision = $events[$m['key']]['context']['data']['decision'] ?? 'pending'; ?>
<article class="lab-match" id="match-<?= lab_h($m['key']) ?>" data-lab-search="<?= lab_h($m['home'] . ' ' . $m['away'] . ' ' . $m['league']) ?>"><div class="lab-rank"><?= str_pad((string)($rank + 1), 2, '0', STR_PAD_LEFT) ?></div><div class="lab-match-body"><div class="lab-meta"><?= lab_h($m['league']) ?> · <?= lab_h((new DateTimeImmutable($m['kickoff']))->setTimezone(new DateTimeZone('Europe/Paris'))->format('d/m H:i')) ?> Paris</div><h2><a href="<?= lab_h($labBase . 'match.php?id=' . $run['id'] . '&match=' . $m['key']) ?>"><?= lab_h($m['home']) ?> <span>—</span> <?= lab_h($m['away']) ?></a></h2><p><?= lab_h($diagnostic['title']) ?></p><?php if (isset($m['assessment'])): ?><p class="lab-muted"><?= lab_h($diagnostic['message']) ?></p><?php endif; ?><div class="lab-flags"><span><?= $past ? 'Match commencé · archive' : 'Prématch' ?></span><span><?= $decision === 'retained' ? 'Retenu par vous' : ($decision === 'excluded' ? 'Écarté par vous' : ($pick ? 'Sélection statistique' : ($diagnostic['state'] === 'data_missing' ? 'Données à compléter' : 'Critères non atteints'))) ?></span></div><p><a class="lab-muted" href="<?= lab_h($labBase . 'match.php?id=' . $run['id'] . '&match=' . $m['key'] . '#contexte') ?>">Fiche et résultat de l’analyse →</a></p><?php require __DIR__ . '/gpt-card.php'; require __DIR__ . '/score-card.php'; ?></div><div class="lab-prob"><?php if ($pick): ?><strong><?= lab_p($pick['probability']) ?></strong><span>estimation du modèle</span><small><?= $pick['odds'] === null ? 'Cote non fournie' : 'Cote exportée ' . number_format($pick['odds'], 2, ',', ' ') ?></small><?php if (isset($pick['stress_ev'])): ?><span>Espérance en scénario prudent : <?= lab_p($pick['stress_ev']) ?></span><?php endif; ?><?php else: ?>—<?php endif; ?></div></article><?php endforeach; ?></div>
<?php require __DIR__ . '/diagnostics.php'; ?>
<?php if ($analysis['errors']): ?><details class="lab-panel"><summary>Lignes non analysées / erreurs de cotes</summary><ul><?php foreach ($analysis['errors'] as $e): ?><li><?= lab_h($e['file'] . ' · ligne ' . $e['row'] . ' : ' . $e['message']) ?></li><?php endforeach; ?></ul></details><?php endif; ?>
<?php endif; lab_end(); ?>
