<?php
declare(strict_types=1);
require __DIR__ . '/bootstrap.php';
require __DIR__ . '/layout.php';
$m = null; $run = null; $log = []; $latest = [];
try {
    if (!$labError) {
        $run = $labStore->get((string)($_GET['id'] ?? ''), $labOwner);
        $m = lab_find_match($run, (string)($_GET['match'] ?? ''));
        $log = array_values(array_filter($labStore->events($run['id'], $labOwner), static function ($e) use ($m) { return $e['match_key'] === $m['key']; }));
        $latest = lab_latest($log)[$m['key']] ?? [];
    }
} catch (Throwable $e) { $labError = 'Match introuvable ou inaccessible.'; }
lab_start($m ? $m['home'] . ' — ' . $m['away'] : 'Fiche du match', 'analyses');
if (!$m || $labError) { lab_end(); exit; }
$assessment = $m['assessment'] ?? null;
$pick = $m['pick']; $diagnostic = \StratEdgeLab\DecisionEngine::diagnostic($m); if ($assessment) { $assessment['explanation'] = $diagnostic['message']; } $past = strtotime($m['kickoff']) <= time();
$context = $latest['context']['data'] ?? [];
$research = $latest['research']['data'] ?? null;
$result = $latest['result']['data'] ?? null;
function lab_match_fields(): void { global $run, $m; echo lab_token(); ?><input type="hidden" name="id" value="<?= lab_h($run['id']) ?>"><input type="hidden" name="match" value="<?= lab_h($m['key']) ?>"><?php }
?>
<p class="lab-meta"><?= lab_h($m['league']) ?> · <?= lab_h((new DateTimeImmutable($m['kickoff']))->setTimezone(new DateTimeZone('Europe/Paris'))->format('d/m/Y H:i')) ?> Paris <a href="<?= lab_h($labBase . 'index.php?id=' . $run['id']) ?>">Retour à la journée</a></p>
<section class="lab-pick"><div><div class="lab-eyebrow"><?= $pick ? 'PISTE STATISTIQUE À EXAMINER' : 'DIAGNOSTIC DU MATCH' ?></div><h2><?= lab_h($diagnostic['title']) ?></h2><p><?= $past ? 'Match commencé : analyse archivée.' : ($pick ? 'Le contexte est à examiner avant de retenir ce choix.' : lab_h($diagnostic['message'])) ?></p></div><?php if ($pick): ?><div class="lab-prob"><strong><?= lab_p($pick['probability']) ?></strong><span>estimation expérimentale</span></div><?php endif; ?></section>
<?php if ($pick): ?><div class="lab-stats"><div><small>Le prix importé</small><strong><?= $pick['odds'] === null ? '—' : number_format($pick['odds'], 2, ',', ' ') ?></strong><span>cote de l’export · non actualisée</span></div><div><small>Espérance théorique</small><strong><?= $pick['ev'] === null ? '—' : lab_p($pick['ev']) ?></strong><span>espérance selon le modèle non calibré</span></div><div><small>Échantillons</small><strong><?= $m['stats']['home_n'] ?> / <?= $m['stats']['away_n'] ?></strong><span>matchs dans les échantillons</span></div></div><?php endif; ?>
<?php if (isset($m['footystats'])): $fs = $m['footystats']; ?>
<section class="lab-panel"><div class="lab-eyebrow">FootyStats</div><h2><?= $fs['status'] === 'enriched' ? 'Bilans séparés par lieu' : 'Enrichissement indisponible' ?></h2><p><?= lab_h($fs['message']) ?></p>
<?php if ($fs['status'] === 'enriched'): ?>
<p class="lab-muted">Statistiques de saison arrêtées au <?= lab_h($fs['as_of']) ?>. Match FootyStats <?= (int)$fs['match_id'] ?> · saison <?= (int)$fs['season_id'] ?>.</p>
<div class="lab-table-scroll"><table><thead><tr><th>Statistique</th><th><?= lab_h($m['home']) ?> à domicile</th><th><?= lab_h($m['away']) ?> à l’extérieur</th></tr></thead><tbody>
<?php foreach (['n' => 'Matchs joués', 'gf' => 'Buts marqués / match', 'ga' => 'Buts encaissés / match', 'over15' => '+1,5 buts (%)', 'over25' => '+2,5 buts (%)', 'over35' => '+3,5 buts (%)', 'xg_for' => 'xG produits / match', 'xg_against' => 'xG concédés / match'] as $field => $label): ?>
<tr><th><?= lab_h($label) ?></th><?php foreach (['home', 'away'] as $side): ?><td><?= $fs[$side][$field] === null ? '—' : lab_h(number_format($fs[$side][$field], $field === 'n' ? 0 : 2, ',', ' ')) ?></td><?php endforeach; ?></tr>
<?php endforeach; ?></tbody></table></div><p class="lab-muted">Ces bilans de saison remplacent les moyennes générales PackBall dans le calcul. Les xG sont affichés à titre descriptif. Les données PackBall et les cotes d’origine restent archivées.</p>
<?php endif; ?></section>
<?php endif; ?>
<?php if ($diagnostic['state'] === 'data_missing'): ?><p class="lab-notice">Analyse impossible faute de données : les probabilités affichées ci-dessous sont descriptives, non utilisables pour sélectionner un pari. Les bilans globaux PackBall ne remplacent pas les historiques par lieu.</p><?php endif; ?>
<?php require __DIR__ . '/history-context.php'; ?>
<?php if ($assessment): require __DIR__ . '/assessment-view.php'; endif; ?>
<section class="lab-panel"><h2>Ce qui produit cette estimation</h2><?php if ($assessment): ?><p>Le modèle croise les attaques et les défenses, rapproche les petits échantillons de la moyenne de leur ligue et intègre l’incertitude des intensités de buts avec une distribution Gamma-Poisson. Les fréquences observées servent de contrôles de cohérence. Les tirs, la possession et les points par match documentent le profil des équipes sans bonus arbitraire de probabilité.</p><?php else: ?><p>Cette archive utilise la référence Poisson initiale fondée sur les moyennes de buts.</p><?php endif; ?><div class="lab-table-scroll"><table><thead><tr><th>Période</th><th>Domicile marque / encaisse</th><th>Extérieur marque / encaisse</th><th>Buts attendus domicile / extérieur</th></tr></thead><tbody><?php foreach (['ft' => ['Match', ''], 'h1' => ['1re mi-temps', 'h1_'], 'h2' => ['2e mi-temps', 'h2_']] as $period => $p): if (!isset($m['lambdas'][$period])) { continue; } ?><tr><th><?= lab_h($p[0]) ?></th><td><?= lab_h($m['stats'][$p[1] . 'home_gf'] . ' / ' . $m['stats'][$p[1] . 'home_ga']) ?></td><td><?= lab_h($m['stats'][$p[1] . 'away_gf'] . ' / ' . $m['stats'][$p[1] . 'away_ga']) ?></td><td><?= lab_h(number_format($m['lambdas'][$period]['home'], 2, ',', '') . ' / ' . number_format($m['lambdas'][$period]['away'], 2, ',', '')) ?></td></tr><?php endforeach; ?></tbody></table></div><p class="lab-muted">Une probabilité élevée ne garantit pas le résultat. Ces estimations n’ont pas encore été calibrées sur un historique indépendant.</p><?php if ($m['warnings']): ?><ul><?php foreach ($m['warnings'] as $warning): ?><li><?= lab_h($warning) ?></li><?php endforeach; ?></ul><?php endif; ?></section>
<section class="lab-panel" id="contexte"><h2>Analyse approfondie du contexte</h2><p>Copie les sélections depuis Analyses dans une conversation ChatGPT. GPT y étudiera le contexte et proposera une décision sourcée. Tu peux ensuite conserver sa conclusion ci-dessous.</p><ul><li>Compositions officielles ou probables, blessures, suspensions et qualité des remplaçants.</li><li>Matchs précédents et suivants, jours de repos, déplacements et rotation, notamment autour des compétitions européennes.</li><li>Enjeux, styles de jeu et confrontations tactiques.</li><li>Météo au stade, vent, pluie, chaleur et état de la pelouse.</li><li>Situation du club : entraîneur, tensions ou événements documentés, sans transformer les rumeurs en faits.</li></ul><p class="lab-muted">Chaque élément doit être relié au pari étudié. Les compositions probables restent à confirmer avant le coup d’envoi. Aucun bonus arbitraire n’est ajouté à la probabilité.</p>
<?php if ($research): ?><div class="lab-research"><h3>Verdict GPT : <?= lab_h(['retained'=>'Retenu', 'pending'=>'À attendre', 'excluded'=>'Écarté'][$research['decision'] ?? 'pending'] ?? 'À attendre') ?></h3><p><?= lab_h($research['reason'] ?? 'Analyse antérieure sans verdict automatique.') ?></p><h3>Analyse GPT · <?= lab_h($research['checked_at']) ?></h3><p class="lab-muted">Les points inconnus restent explicites. Une décision GPT reste une appréciation du contexte, sans garantie sur le résultat.</p><div class="lab-prose"><?= nl2br(lab_h($research['text'])) ?></div><h3>Sources de la recherche</h3><ul><?php foreach ($research['sources'] as $s): if (!lab_url($s['url'])) { continue; } ?><li><a href="<?= lab_h($s['url']) ?>" target="_blank" rel="noopener noreferrer"><?= lab_h($s['title']) ?></a></li><?php endforeach; ?></ul></div><?php endif; ?>
<form method="post" action="<?= lab_h($labBase) ?>action.php" class="lab-form"><?php lab_match_fields(); ?><input type="hidden" name="action" value="context"><fieldset <?= $past ? 'disabled' : '' ?>><legend>Conclusion de l’analyse dans ChatGPT</legend><label>Décision<select name="decision"><?php foreach (['pending' => 'À examiner', 'retained' => 'Retenir le choix', 'excluded' => 'Écarter le choix'] as $v => $text): ?><option value="<?= $v ?>" <?= ($context['decision'] ?? 'pending') === $v ? 'selected' : '' ?>><?= lab_h($text) ?></option><?php endforeach; ?></select></label><label>Faits vérifiés, inconnues et raison de la décision<textarea name="note" rows="5" maxlength="6000" placeholder="Compositions, absences, calendrier, contexte…"><?= lab_h($context['note'] ?? '') ?></textarea></label><label>Lien source principal · facultatif<input type="url" name="source" maxlength="2000" value="<?= lab_h($context['source'] ?? '') ?>"></label><button class="lab-button">Enregistrer la conclusion</button></fieldset></form></section>
<section class="lab-panel"><h2>Marchés comparés</h2><div class="lab-table-scroll"><table><thead><tr><th>Pari</th><th>Probabilité</th><th>Cote exportée</th><th>Décision</th></tr></thead><tbody><?php $candidates = $m['candidates']; usort($candidates, static function ($a, $b) { return $b['probability'] <=> $a['probability']; }); foreach ($candidates as $c): ?><tr class="<?= $pick && $c['id'] === $pick['id'] ? 'lab-chosen' : '' ?>"><td><?= lab_h($c['label']) ?></td><td><?= lab_p($c['probability']) ?></td><td><?= $c['odds'] === null ? '—' : number_format($c['odds'], 2, ',', ' ') ?></td><td class="lab-reason-cell"><?= $c['eligible'] ? 'Passe les critères statistiques' : lab_h(implode(' ', $c['reasons'] ?? ['Hors filtres'])) ?></td></tr><?php endforeach; ?></tbody></table></div></section>
<?php if ($pick): ?><section class="lab-panel"><h2>Enregistrer le résultat</h2><p>Score de la période <strong><?= lab_h(['ft' => 'match entier (90 minutes et arrêts de jeu)', 'h1' => 'première mi-temps seulement', 'h2' => 'deuxième mi-temps seulement'][$pick['period']]) ?></strong>. Aucune prolongation. Pour la deuxième mi-temps, utilise uniquement les buts marqués après la pause.</p><?php if ($result): ?><p class="lab-notice">Dernier règlement : <?= lab_h(['won' => 'gagné', 'lost' => 'perdu', 'void' => 'annulé'][$result['outcome']]) ?>. Une correction sera ajoutée à l’historique.</p><?php endif; ?>
<form method="post" action="<?= lab_h($labBase) ?>action.php" class="lab-form"><?php lab_match_fields(); ?><input type="hidden" name="action" value="result"><div class="lab-grid"><label>Buts domicile<input type="number" min="0" max="30" step="1" name="score_home" value="<?= lab_h($result['home'] ?? '') ?>"></label><label>Buts extérieur<input type="number" min="0" max="30" step="1" name="score_away" value="<?= lab_h($result['away'] ?? '') ?>"></label><label>Source du score<input type="url" name="result_source" maxlength="2000" value="<?= lab_h($result['source'] ?? '') ?>"></label><label>Note / motif de correction<input name="result_note" maxlength="2000"></label></div><label class="lab-check"><input type="checkbox" name="void"> Pari annulé</label><label class="lab-check"><input type="checkbox" name="confirm_result" required> La période est terminée et le résultat a été vérifié.</label><button class="lab-button lab-secondary" <?= !$past ? 'disabled' : '' ?>>Enregistrer le règlement</button></form></section><?php endif; ?>
<details class="lab-panel"><summary>Traçabilité · <?= lab_h($run['data']['analysis']['version']) ?></summary><p>Prévision initiale : <?= lab_h($run['data']['analysis']['generated_at']) ?>. Les contrôles et corrections sont ajoutés sans la remplacer.</p><ul><?php foreach ($log as $event): ?><li><?= lab_h($event['created_at'] . ' · ' . ['context' => 'Contrôle', 'research' => 'Recherche web', 'result' => 'Règlement'][$event['kind']]) ?><?php if ($event['kind'] === 'context'): ?> : <?= lab_h($event['data']['decision'] . ' — ' . $event['data']['note']) ?><?php elseif ($event['kind'] === 'result'): ?> : <?= lab_h($event['data']['outcome'] . ' — ' . ($event['data']['note'] ?? '')) ?><?php endif; ?></li><?php endforeach; ?></ul></details>
<?php lab_end(); ?>
