/* V4 separates Packball import from the research download. */
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const root=path.resolve(__dirname,'../public/admin/slate/live90/assets');
const elements=new Map(),el=k=>{if(!elements.has(k))elements.set(k,{value:'2099-09-25',content:'csrf',textContent:'',innerHTML:'',hidden:false,style:{},dataset:{},classList:{toggle(){},add(){},remove(){}},close(){},showModal(){},click(){this.onclick?.()},addEventListener(){}});return elements.get(k)};
let downloaded,posted,exported;const a=Array(72).fill('1'),b=Array(47).fill('1');for(const r of [a,b]){r[0]='France';r[2]='Ligue';r[3]='20:45';r[4]='NS';r[5]='Équipe A';r[8]='Équipe B'}a[24]=a[25]='10';a[26]=a[27]='12';a[30]=a[31]='4';
const board={matches:[],signals:[],totals:{},feed:{},settings:{},telegram:{},server_time:new Date().toISOString()};
const c=vm.createContext({console,Intl,Date,Map,Set,window:{},document:{querySelector:el,querySelectorAll:()=>[],addEventListener(){},createElement:()=>({click(){}})},setInterval(){},setTimeout(){},Blob:class{constructor(parts){downloaded=JSON.parse(parts[0])}},URL:{createObjectURL(){return 'blob:test'},revokeObjectURL(){}},fetch:async(url,o)=>{if(o.method==='GET')return {ok:true,json:async()=>board};const x=JSON.parse(o.body);if(x.action==='packball'){posted=x;exported={schema:'stratedge.research.v4',timezone:'Europe/Paris',matches:x.bundle.matches};return{ok:true,json:async()=>({ok:true,imported:1,preserved:0,late:0})}}if(x.action==='export_analysis')return{ok:true,json:async()=>exported};throw Error('Unexpected action')}});
vm.runInContext(fs.readFileSync(path.join(root,'packball.js'),'utf8'),c);vm.runInContext(fs.readFileSync(path.join(root,'app.js'),'utf8'),c);
const csv=rows=>rows.map(r=>r.join(';')).join('\n');el('#packball-files').files=[{size:100,text:async()=>csv([Array(72).fill('h'),a])},{size:100,text:async()=>csv([Array(47).fill('h'),b])}];el('#packball-day').value='2099-09-25';
(async()=>{await el('#packball-save').onclick();assert.equal(posted.action,'packball');assert.equal(posted.bundle.schema,'stratedge.packball.v4');assert.equal(posted.bundle.matches[0].match_id,null);assert.equal(posted.bundle.matches[0].kickoff,'2099-09-25T18:45:00.000Z');assert.equal(downloaded,undefined);await el('#export-analysis').onclick();assert.equal(downloaded.schema,'stratedge.research.v4');assert.equal(downloaded.matches[0].home,'Équipe A');console.log('V4 : import CSV séparé, fuseau Paris et export pour GPT validés.');})().catch(e=>{console.error(e);process.exitCode=1});
